/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazProyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Hp EliteBook
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Desk = new javax.swing.JDesktopPane();
        BtnExplosion = new javax.swing.JButton();
        BtnBilling = new javax.swing.JButton();
        BtnRegisterVehicle = new javax.swing.JButton();
        BtnRequest = new javax.swing.JButton();
        BtnRegisterCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnSignOff = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMFile = new javax.swing.JMenu();
        jMEdit = new javax.swing.JMenu();
        jMSave = new javax.swing.JMenu();
        jMHelp = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnExplosion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazProyecto/imagenes/explosion.png"))); // NOI18N

        BtnBilling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazProyecto/imagenes/facturacion.png"))); // NOI18N

        BtnRegisterVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazProyecto/imagenes/registrar vehiculo.png"))); // NOI18N

        BtnRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazProyecto/imagenes/solicitud.png"))); // NOI18N
        BtnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRequestActionPerformed(evt);
            }
        });

        BtnRegisterCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazProyecto/imagenes/registro de cliente.png"))); // NOI18N
        BtnRegisterCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterCustomerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Quebradores del SUR");

        BtnSignOff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnSignOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazProyecto/imagenes/cerrar-sesion.png"))); // NOI18N
        BtnSignOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignOffActionPerformed(evt);
            }
        });

        Desk.setLayer(BtnExplosion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desk.setLayer(BtnBilling, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desk.setLayer(BtnRegisterVehicle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desk.setLayer(BtnRequest, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desk.setLayer(BtnRegisterCustomer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desk.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desk.setLayer(BtnSignOff, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DeskLayout = new javax.swing.GroupLayout(Desk);
        Desk.setLayout(DeskLayout);
        DeskLayout.setHorizontalGroup(
            DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeskLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeskLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnBilling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnRegisterCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addGroup(DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnExplosion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addGap(105, 105, 105)
                .addGroup(DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnRegisterVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(BtnSignOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132))
        );
        DeskLayout.setVerticalGroup(
            DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeskLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegisterCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegisterVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(DeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnSignOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBilling, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(BtnExplosion, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jMFile.setText("File");
        jMenuBar1.add(jMFile);

        jMEdit.setText("Edit");
        jMenuBar1.add(jMEdit);

        jMSave.setText("Save");
        jMenuBar1.add(jMSave);

        jMHelp.setText("Help");
        jMenuBar1.add(jMHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Desk)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desk)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegisterCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterCustomerActionPerformed
        RegisterCustomer ventana = new RegisterCustomer();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnRegisterCustomerActionPerformed

    private void BtnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRequestActionPerformed
         Requests ventana = new Requests();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnRequestActionPerformed

    private void BtnSignOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignOffActionPerformed

        Login ventana = new Login();
        ventana.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(this,"Hasta luego ");
    }//GEN-LAST:event_BtnSignOffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBilling;
    private javax.swing.JButton BtnExplosion;
    private javax.swing.JButton BtnRegisterCustomer;
    private javax.swing.JButton BtnRegisterVehicle;
    private javax.swing.JButton BtnRequest;
    private javax.swing.JButton BtnSignOff;
    private javax.swing.JDesktopPane Desk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMEdit;
    private javax.swing.JMenu jMFile;
    private javax.swing.JMenu jMHelp;
    private javax.swing.JMenu jMSave;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

   
}
